### ISSUE TITLE
Echo

### ISSUE THREAD

**Issue by 7xn1** [3kh0/google-chrome-python#18]
Hello Echo I saw you sent me a pull request please send me it back through a diffrent repo

**Comment by 7xn1** [comment]
I didnt notice and would like to ask a few questions

**Comment by 3kh0** [comment]
@Olivem1234567 Which repo would you like to send it to? Also I would prefer email over github issues since other people can see this 0.0

**Comment by 7xn1** [comment]
Ok I sent you a email so we can talk over that

**Comment by 3kh0** [comment]
Ok

**Comment by 7xn1** [comment]
im at school rn so like i cant rlly email you until like 3:30
